-- Core portfolio schema for a fresh Supabase project.
-- Run this before the later enhancement and RLS migrations.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null default '',
  slug text not null default '',
  type text not null default 'video'
    check (type in ('video', 'graphic', 'both')),
  active boolean not null default true,
  order_num integer not null default 0,
  description text,
  cover_image_url text,
  thumbnail_image text,
  icon text,
  seo_title text,
  seo_description text,
  canonical_url text,
  og_image_url text,
  og_image text,
  show_on_homepage boolean not null default true,
  show_on_portfolio boolean not null default true,
  show_on_portfolio_page boolean not null default true,
  show_filter_chip boolean not null default true,
  featured boolean not null default false,
  featured_category boolean not null default false,
  visibility_status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text not null default '',
  slug text,
  category text not null default '',
  youtube_url text not null default '',
  thumbnail text not null default '',
  tier text not null default 'standard',
  description text,
  order_num integer not null default 0,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.graphics (
  id uuid primary key default gen_random_uuid(),
  title text not null default '',
  slug text,
  category text not null default '',
  image_url text not null default '',
  description text,
  visible boolean not null default true,
  order_num integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tutorials (
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text not null default '',
  youtube_url text not null default '',
  thumbnail text not null default '',
  category text not null default '',
  duration text not null default '',
  level text not null default '',
  order_num integer not null default 0,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.navigation (
  id text primary key,
  label text not null default '',
  href text not null default '/',
  order_num integer not null default 0,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  path text not null default '',
  user_agent text,
  referrer text,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists set_videos_updated_at on public.videos;
create trigger set_videos_updated_at
before update on public.videos
for each row execute function public.set_updated_at();

drop trigger if exists set_graphics_updated_at on public.graphics;
create trigger set_graphics_updated_at
before update on public.graphics
for each row execute function public.set_updated_at();

drop trigger if exists set_tutorials_updated_at on public.tutorials;
create trigger set_tutorials_updated_at
before update on public.tutorials
for each row execute function public.set_updated_at();

drop trigger if exists set_navigation_updated_at on public.navigation;
create trigger set_navigation_updated_at
before update on public.navigation
for each row execute function public.set_updated_at();

create index if not exists site_settings_key_idx
  on public.site_settings (key);

create unique index if not exists categories_slug_type_idx
  on public.categories (slug, type);

create index if not exists videos_visible_order_idx
  on public.videos (visible, order_num);

create index if not exists graphics_visible_order_idx
  on public.graphics (visible, order_num, created_at desc);

create index if not exists tutorials_visible_order_idx
  on public.tutorials (visible, order_num);

create index if not exists navigation_visible_order_idx
  on public.navigation (visible, order_num);

insert into storage.buckets (id, name, public)
values
  ('media', 'media', true),
  ('graphics', 'graphics', true)
on conflict (id) do update
set public = excluded.public;

alter table public.site_settings enable row level security;
alter table public.categories enable row level security;
alter table public.videos enable row level security;
alter table public.graphics enable row level security;
alter table public.tutorials enable row level security;
alter table public.navigation enable row level security;
alter table public.page_views enable row level security;
